language: python

sudo: required
dist: xenial

install: "pip install -Ue .[test]"

python:
  - "3.5"
  - "3.6"
  - "3.7"

script: coverage run --source=tktitler setup.py test

after_success:
  coveralls
